# 版本定义
version: '1'

networks:
  app-networks:
    driver: bridge

# 数据卷：持久化数据（删除容器不丢数据）
volumes:
  mysql-data:
  redis-data:
  rabbitmq-data:

# 定义所有服务（容器）
services:
  # 1. MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: project-mysql
    networks:
      - app-networks
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: private_cloud_disk # 自动创建数据库
    volumes:
      - mysql-data:/var/lib/mysql # 数据持久化（删容器不丢数据）
      # 2. 自动执行本地SQL（初始化你的所有表+数据）
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:latest
    container_name: project-redis
    networks:
      - app-networks
    restart: always
    ports:
      - "6389:6379"
    volumes:
      - redis-data:/data
    hostname: redis

  rabbitmq:
    image: rabbitmq:latest
    container_name: project-rabbitmq
    networks:
      - app-networks
    restart: always
    ports:
      - "5673:5672"    # 程序连接端口
      - "15673:15672"  # 管理面板端口
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
       - rabbitmq-data:/var/lib/rabbitmq

  # 2. SpringBoot 后端业务服务
  platform-service-backend:
    build: ./PrivateCloudDisk-platform-service # 自动读取前端Dockerfile
    container_name: backend-platform-service
    networks:
      - app-networks
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - rabbitmq
    # 开发环境热重载
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # 连接数据库：用服务名访问（Docker内部网络）
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/private_cloud_disk?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBItMQ_PORT: 5672
    # 核心：本地代码目录挂载到容器 → 改代码实时生效，不用重新build
    volumes:
      - ./PrivateCloudDisk-platform-service:/backend_platform_service
      - /backend_platform_service/.gradle
      - /backend_platform_service/.idea
      - /backend_platform_service/build
      - /backend_platform_service/out
  
  # 3. FastAPI 后端文件服务
  file-service-backend:
    build: ./PrivateCloudDisk-shortage-service
    container_name: backend-file-service
    networks:
      - app-networks
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - platform-service-backend
     # 核心：本地代码目录挂载到容器 → 改代码实时生效，不用重新build
    volumes:
      - ./PrivateCloudDisk-shortage-service:/backend_file_service
      - /backend_file_service/__pycache__
      - /backend_file_service/.venv

  # 4. Vue 前端服务
  frontend:
    build: ./PrivateCloudDisk-web # 自动读取后端Dockerfile
    container_name: private-cloud-web
    networks:
      - app-networks
    restart: always
    ports:
      - "5500:5500"
    depends_on:
      - platform-service-backend # 等待数据库启动后再启动后端
      - file-service-backend
     # 核心：本地代码目录挂载到容器 → 改代码实时生效，不用重新build
    volumes:
      - ./PrivateCloudDisk-web:/frontend_web_app
      - /frontend_web_app/dist
      - /frontend_web_app/node_modules