apisix:
  node_listen: 9080
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

wasm:
  plugins:
    - name: coraza-filter
      priority: 7999
      file: /usr/local/apisix/proxywasm/coraza-proxy-wasm.wasm

plugins:
  - real-ip              # 真实 IP 获取
  - ip-restriction       # IP 黑白名单
  - limit-count          # 请求速率限制
  - limit-conn           # 并发连接限制
  - ua-restriction       # User-Agent 限制
  - proxy-rewrite        # 代理路径重写
  - cors                 # 跨域
  - prometheus           # 监控指标