# ========== 监听 ==========
listeners.tcp.default = 5672

# ========== 管理插件 ==========
management.tcp.port = 15672
management.tcp.ip   = 0.0.0.0

# ========== 磁盘与内存告警 ==========
vm_memory_high_watermark.relative = 0.4
disk_free_limit.absolute          = 1GB

# ========== 默认用户（可通过环境变量覆盖） ==========
default_user  = guest
default_pass  = guest

# ========== 日志 ==========
log.console.level = info
log.console       = true