spring.application.name=PrivateCloudDisk-platform-service
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/private_cloud_disk
spring.datasource.username=root
spring.datasource.password=20070315mwz
mybatis.mapper-locations=classpath:mapper/*.xml
# RabbitMQ ??
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
# Redis ??
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.pool.max-wait=-1ms


internal:
    api:
        allowed-ips:
            - 127.0.0.1
            - localhost
        protected-paths:
            - /internal/storage/**
        exclude-paths: []