<template>
  <div class="public-discovery min-h-screen bg-[#f6f8fa]"><header class="border-b border-[#d0d7de] bg-white"><div class="mx-auto flex max-w-6xl items-center gap-4 px-4 py-4 lg:px-8"><button class="back-link" @click="router.back()"><i class="fa fa-arrow-left mr-2"></i>返回</button><h1 class="text-lg font-semibold">探索公开仓库</h1></div></header><main class="mx-auto max-w-6xl px-4 py-8 lg:px-8"><section class="explore-hero"><p class="text-xs font-semibold uppercase tracking-[.18em] text-[#0969da]">Public repositories</p><h2 class="mt-2 text-3xl font-bold">发现值得收藏的资源仓库</h2><p class="mt-2 text-sm text-[#57606a]">浏览登录用户公开发布的项目资料、文档与可下载资源。</p><div class="mt-5 flex gap-2"><input v-model.trim="keyword" class="explore-input" placeholder="搜索仓库名称或描述" @keyup.enter="load" /><button class="explore-button" @click="load"><i class="fa fa-search mr-1"></i>搜索</button></div></section><div class="mt-8 flex items-center justify-between"><h2 class="text-xl font-semibold">{{ keyword ? '搜索结果' : '推荐仓库' }}</h2><span class="text-sm text-[#57606a]">{{ repositories.length }} 个</span></div><div v-if="loading" class="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><div v-for="i in 6" :key="i" class="repo-card animate-pulse"><div class="h-5 w-2/3 rounded bg-[#eaeef2]"></div><div class="mt-3 h-4 rounded bg-[#eaeef2]"></div></div></div><div v-else-if="!repositories.length" class="profile-empty mt-4">暂时没有匹配的公开仓库</div><div v-else class="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><article v-for="repo in repositories" :key="repo.spaceId" class="repo-card cursor-pointer" @click="router.push(`/repo/${repo.spaceId}`)"><div class="flex items-center justify-between"><h3 class="truncate font-semibold text-[#0969da]">{{ repo.spaceName }}</h3><span class="public-badge">Public</span></div><p class="mt-2 line-clamp-3 text-sm leading-6 text-[#57606a]">{{ repo.description || '暂无描述' }}</p><div class="mt-4 flex items-center justify-between text-xs text-[#57606a]"><span>@{{ repo.ownerName }}</span><span>{{ repo.fileCount || 0 }} 个文件</span></div></article></div></main></div>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { explorePublicSpacesApi, type PublicSpaceDetail } from '@/api/modules/publicSpaces'
const router = useRouter(); const keyword = ref(''); const repositories = ref<PublicSpaceDetail[]>([]); const loading = ref(false)
async function load() { loading.value = true; try { repositories.value = (await explorePublicSpacesApi(keyword.value)).data || [] } finally { loading.value = false } } onMounted(load)
</script>
<style scoped>
.explore-hero,.repo-card { border:1px solid #d0d7de;border-radius:8px;background:#fff;padding:22px; }.explore-hero { background:linear-gradient(135deg,#ddf4ff,#fff); }.explore-input { min-height:42px;flex:1;border:1px solid #d0d7de;border-radius:6px;padding:0 12px;outline:none; }.explore-input:focus { border-color:#0969da;box-shadow:0 0 0 3px rgba(9,105,218,.12); }.explore-button { min-height:42px;border-radius:6px;background:#2da44e;padding:0 18px;color:#fff;font-size:13px; }.back-link { color:#0969da;font-size:13px; }.public-badge { border:1px solid #d0d7de;border-radius:999px;padding:1px 7px;font-size:11px;color:#57606a; }.repo-card { transition:box-shadow .15s,transform .15s; }.repo-card:hover { box-shadow:0 5px 16px rgba(27,31,36,.1);transform:translateY(-1px); }.profile-empty { border:1px dashed #d0d7de;border-radius:8px;padding:56px;text-align:center;color:#57606a; }
</style>
