<template>
  <div class="public-discovery min-h-screen bg-[#f6f8fa]"><header class="border-b border-[#d0d7de] bg-white"><div class="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 lg:px-8"><button class="back-link" @click="router.back()"><i class="fa fa-arrow-left mr-2"></i>返回</button><router-link to="/explore" class="back-link">探索公开仓库</router-link></div></header><main class="mx-auto grid max-w-6xl gap-6 px-4 py-8 lg:grid-cols-[260px_minmax(0,1fr)] lg:px-8"><aside class="profile-card"><div class="profile-avatar">{{ profile?.displayName?.slice(0,1) || '?' }}</div><h1 class="mt-4 text-xl font-semibold">{{ profile?.displayName || username }}</h1><p class="mt-1 text-sm text-[#57606a]">@{{ profile?.username || username }}</p><p class="mt-4 text-sm text-[#57606a]">公开仓库 {{ profile?.repositories?.length || 0 }} 个</p><router-link v-if="isSelf" to="/app/profile" class="mt-5 inline-flex text-sm text-[#0969da]">编辑个人资料</router-link></aside><section><div class="mb-4"><h2 class="text-xl font-semibold">公开仓库</h2><p class="mt-1 text-sm text-[#57606a]">{{ profile?.displayName || username }} 创建的持续维护资源。</p></div><div v-if="loading" class="grid gap-4 sm:grid-cols-2"><div v-for="i in 4" :key="i" class="repo-summary animate-pulse"><div class="h-5 w-2/3 rounded bg-[#eaeef2]"></div><div class="mt-3 h-4 rounded bg-[#eaeef2]"></div></div></div><div v-else-if="!profile?.repositories?.length" class="profile-empty">暂无公开仓库</div><div v-else class="grid gap-4 sm:grid-cols-2"><article v-for="repo in profile.repositories" :key="repo.spaceId" class="repo-summary" @click="router.push(`/repo/${repo.spaceId}`)"><div class="flex items-center justify-between"><h3 class="truncate font-semibold text-[#0969da]">{{ repo.spaceName }}</h3><span class="public-badge">Public</span></div><p class="mt-2 line-clamp-2 text-sm text-[#57606a]">{{ repo.description || '暂无描述' }}</p><div class="mt-4 text-xs text-[#57606a]">{{ repo.fileCount || 0 }} 个文件 · 更新于 {{ formatDate(repo.updatedAt) }}</div></article></div></section></main></div>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { useAuthStore } from '@/stores/authStore'; import { getPublicUserProfileApi, type PublicUserProfile } from '@/api/modules/publicSpaces'
const route = useRoute(); const router = useRouter(); const auth = useAuthStore(); const username = String(route.params.username); const loading = ref(true); const profile = ref<PublicUserProfile | null>(null); const isSelf = computed(() => auth.user?.name === username || auth.user?.account === username)
onMounted(async () => { try { profile.value = (await getPublicUserProfileApi(username)).data } finally { loading.value = false } }); function formatDate(value?: string) { return value ? new Date(value).toLocaleDateString('zh-CN') : '—' }
</script>
<style scoped>
.profile-card,.repo-summary { border:1px solid #d0d7de;border-radius:8px;background:#fff;padding:20px; }.profile-avatar { width:88px;height:88px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#ddf4ff;color:#0969da;font-size:32px;font-weight:700; }.back-link { color:#0969da;font-size:13px; }.public-badge { border:1px solid #d0d7de;border-radius:999px;padding:1px 7px;font-size:11px;color:#57606a; }.repo-summary { cursor:pointer;transition:box-shadow .15s,transform .15s; }.repo-summary:hover { box-shadow:0 5px 16px rgba(27,31,36,.1);transform:translateY(-1px); }.profile-empty { border:1px dashed #d0d7de;border-radius:8px;padding:56px;text-align:center;color:#57606a; }
</style>
