spring.application.name=PrivateCloudDisk-gateway-service
server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=business-service
spring.cloud.gateway.server.webflux.routes[0].uri=${BUSINESS_SERVICE_URL:http://platform-service-backend:8081}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/business/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=2
spring.cloud.gateway.server.webflux.routes[0].filters[1].name=Retry
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.retries=3
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.statuses=BAD_GATEWAY,SERVICE_UNAVAILABLE

spring.cloud.gateway.server.webflux.routes[1].id=file-service
spring.cloud.gateway.server.webflux.routes[1].uri=${FILE_SERVICE_URL:http://file-service-backend:8000}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/files/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=2

jwt.public-key-path=classpath:keys/public_key.pem

logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.project=INFO