<template>
  <main class="min-h-screen bg-neutral-50 px-4 py-6 sm:px-6"><div class="mx-auto max-w-6xl"><header class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><button class="mb-2 text-sm text-neutral-500 hover:text-primary" @click="router.push('/space/manage')"><i class="fa fa-arrow-left mr-1"></i>空间管理</button><h1 class="text-2xl font-bold text-neutral-900">{{ space?.spaceName || '空间' }} · 成员管理</h1><p class="mt-1 text-sm text-neutral-500">邀请成员、调整角色和精细化权限。</p></div><div class="flex gap-2"><button class="rounded-lg border bg-white px-3 py-2 text-sm text-neutral-600 hover:border-primary" @click="router.push(`/space/${spaceId}/members/approvals`)">审批管理</button><button class="rounded-lg bg-primary px-3 py-2 text-sm font-medium text-white hover:bg-primary/90" @click="showInvite = true"><i class="fa fa-plus mr-1"></i>邀请成员</button></div></header>
    <section class="rounded-xl border bg-white shadow-sm"><div class="flex flex-wrap gap-3 border-b p-4"><input v-model.trim="keyword" class="min-w-56 flex-1 rounded-lg border px-3 py-2 text-sm" placeholder="搜索成员用户名" @input="load" /><template v-if="selected.length"><select v-model="bulkRole" class="rounded-lg border px-2 py-2 text-sm"><option value="editor">批量设为编辑者</option><option value="viewer">批量设为只读</option><option value="custom">批量设为自定义</option></select><button class="rounded-lg border border-primary px-3 py-2 text-sm text-primary hover:bg-primary/5" @click="batchRole">应用角色</button><button class="rounded-lg border border-red-200 px-3 py-2 text-sm text-red-500 hover:bg-red-50" @click="batchRemove">批量移除（{{ selected.length }}）</button></template></div><div v-if="loading" class="p-12 text-center text-neutral-400"><i class="fa fa-spinner fa-spin mr-1"></i>加载成员</div><div v-else class="overflow-x-auto"><table class="w-full min-w-[680px] text-left text-sm"><thead class="bg-neutral-50 text-xs text-neutral-500"><tr><th class="w-10 px-4 py-3"><input type="checkbox" :checked="selected.length === members.length && members.length > 0" @change="toggleAll" /></th><th class="px-4 py-3">成员</th><th class="px-4 py-3">角色</th><th class="px-4 py-3">加入时间</th><th class="px-4 py-3 text-right">操作</th></tr></thead><tbody class="divide-y"><template v-for="member in members" :key="member.userId"><tr class="hover:bg-neutral-50"><td class="px-4 py-3"><input v-if="member.role !== 'owner'" v-model="selected" type="checkbox" :value="member.userId" /></td><td class="px-4 py-3"><button class="flex items-center gap-3 text-left" @click="viewProfile(member)"><div class="flex h-9 w-9 items-center justify-center rounded-full bg-primary/10 text-xs font-semibold text-primary">{{ (member.username || member.userId).slice(0, 2).toUpperCase() }}</div><div><p class="font-medium text-neutral-800">{{ member.username || member.userId }}</p><p class="text-xs text-neutral-400">{{ member.userId }}</p></div></button></td><td class="px-4 py-3"><span class="rounded-full bg-neutral-100 px-2 py-1 text-xs text-neutral-600">{{ roleLabel(member.role) }}</span></td><td class="px-4 py-3 text-xs text-neutral-500">{{ member.joinedAt || '—' }}</td><td class="px-4 py-3 text-right"><button v-if="member.role !== 'owner'" class="mr-3 text-xs text-primary hover:underline" @click="edit(member)">权限设置</button><button v-if="member.role !== 'owner'" class="text-xs text-red-500 hover:underline" @click="remove(member)">移除</button><span v-else class="text-xs text-neutral-400">空间所有者</span></td></tr><tr v-if="expanded === member.userId" class="bg-neutral-50"><td colspan="5" class="px-14 py-3 text-xs text-neutral-500">{{ profiles[member.userId]?.description || '暂无公开简介' }} <span v-if="profiles[member.userId]?.account" class="ml-3">账号：{{ profiles[member.userId]?.account }}</span></td></tr></template></tbody></table></div></section>
    <Teleport to="body"><div v-if="editing" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" @click.self="editing = null"><div class="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 class="text-lg font-semibold">设置成员权限</h2><p class="mt-1 text-xs text-neutral-400">{{ editing.username || editing.userId }}</p><SpacePermissionMatrix v-model="permissionForm" :target-role="editing.role" class="mt-5" /><div class="mt-6 flex justify-end gap-2"><button class="rounded-lg px-4 py-2 text-sm text-neutral-500 hover:bg-neutral-100" @click="editing = null">取消</button><button class="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white" @click="savePermission">保存</button></div></div></div><div v-if="showInvite" class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" @click.self="showInvite = false"><div class="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 class="text-lg font-semibold">邀请成员</h2><p class="mt-1 text-xs text-neutral-400">输入用户 ID 或用户名，邀请后将按空间策略处理。</p><input v-model.trim="inviteUserId" class="mt-5 w-full rounded-lg border px-3 py-2 text-sm" placeholder="用户 ID" /><select v-model="inviteRole" class="mt-3 w-full rounded-lg border px-3 py-2 text-sm"><option value="editor">编辑者</option><option value="viewer">只读成员</option><option value="admin">管理员</option></select><div class="mt-4 flex items-center gap-2"><button class="rounded-lg border px-3 py-2 text-xs text-primary hover:bg-primary/5" @click="generateInvite">生成邀请链接</button><input v-if="inviteLink" :value="inviteLink" readonly class="min-w-0 flex-1 rounded border bg-neutral-50 px-2 py-2 text-[11px] text-neutral-500" @focus="($event.target as HTMLInputElement).select()" /></div><div class="mt-6 flex justify-end gap-2"><button class="rounded-lg px-4 py-2 text-sm text-neutral-500" @click="showInvite = false">取消</button><button class="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white disabled:opacity-50" :disabled="!inviteUserId" @click="invite">发送邀请</button></div></div></div></Teleport>
  </div></main>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { addMemberApi, createSpaceInvitationApi, getPublicUserProfileApi, getSpaceApi, listCollaborationMembersApi, removeMemberApi, updateMemberPermissionsApi, type PublicUserProfile, type SpaceInfo, type SpaceMember, type SpacePermissionUpdate } from '@/api/modules/space'; import { useToastStore } from '@/stores/toastStore'; import SpacePermissionMatrix from '@/components/space/SpacePermissionMatrix.vue'
const route = useRoute(); const router = useRouter(); const toast = useToastStore(); const spaceId = String(route.params.spaceId); const space = ref<SpaceInfo | null>(null); const members = ref<SpaceMember[]>([]); const selected = ref<string[]>([]); const keyword = ref(''); const loading = ref(false); const editing = ref<SpaceMember | null>(null); const showInvite = ref(false); const inviteUserId = ref(''); const inviteRole = ref<SpaceMember['role']>('editor'); const inviteLink = ref(''); const profiles = ref<Record<string, PublicUserProfile>>({}); const expanded = ref<string | null>(null); const bulkRole = ref<SpaceMember['role']>('editor'); const permissionForm = ref<SpacePermissionUpdate>({ role: 'viewer' })
async function load() { loading.value = true; try { const [s, m] = await Promise.all([getSpaceApi(spaceId), listCollaborationMembersApi(spaceId, keyword.value)]); space.value = s.data; members.value = m.data || [] } catch { toast.showToast('成员加载失败', 'error') } finally { loading.value = false } }
function edit(member: SpaceMember) { editing.value = member; permissionForm.value = { role: member.role } }
async function viewProfile(member: SpaceMember) { expanded.value = expanded.value === member.userId ? null : member.userId; if (expanded.value && !profiles.value[member.userId]) { try { const res = await getPublicUserProfileApi(member.userId); if (res.data) profiles.value[member.userId] = res.data } catch { toast.showToast('成员资料暂时不可用', 'error') } } }
async function savePermission() { if (!editing.value) return; try { await updateMemberPermissionsApi(spaceId, editing.value.userId, permissionForm.value); toast.showToast('成员权限已更新', 'success'); editing.value = null; await load() } catch { toast.showToast('权限更新失败', 'error') } }
async function invite() { try { await addMemberApi(spaceId, inviteUserId.value, inviteRole.value); toast.showToast('成员已邀请', 'success'); showInvite.value = false; inviteUserId.value = ''; await load() } catch { toast.showToast('邀请失败，请检查用户 ID 或权限', 'error') } }
async function generateInvite() { try { const res = await createSpaceInvitationApi(spaceId); inviteLink.value = `${window.location.origin}/teamwork/space/${spaceId}?invite=${res.data}`; await navigator.clipboard?.writeText(inviteLink.value); toast.showToast('邀请链接已生成并复制', 'success') } catch { toast.showToast('邀请链接生成失败', 'error') } }
async function remove(member: SpaceMember) { if (!window.confirm(`确定移除 ${member.username || member.userId} 吗？`)) return; try { await removeMemberApi(spaceId, member.userId); toast.showToast('成员已移除', 'success'); await load() } catch { toast.showToast('移除失败', 'error') } }
async function batchRemove() { if (!window.confirm(`确定移除选中的 ${selected.value.length} 位成员吗？`)) return; for (const id of selected.value) { try { await removeMemberApi(spaceId, id) } catch { /* 单条失败不阻断批量任务 */ } } selected.value = []; await load() }
async function batchRole() { if (!selected.value.length) return; for (const id of selected.value) { try { await updateMemberPermissionsApi(spaceId, id, { role: bulkRole.value }) } catch { /* 单条失败由最终刷新反馈 */ } } selected.value = []; toast.showToast('批量角色更新已提交', 'success'); await load() }
function toggleAll(event: Event) { selected.value = (event.target as HTMLInputElement).checked ? members.value.filter((m) => m.role !== 'owner').map((m) => m.userId) : [] }
function roleLabel(role: string) { return ({ owner: '所有者', admin: '管理员', editor: '编辑者', viewer: '只读成员', custom: '自定义' } as Record<string, string>)[role] || role }
onMounted(load)
</script>
