<template>
  <main class="min-h-screen bg-neutral-50 px-4 py-6 sm:px-6"><div class="mx-auto max-w-5xl"><button class="mb-5 text-sm text-neutral-500 hover:text-primary" @click="router.push(`/space/${spaceId}/members`)"><i class="fa fa-arrow-left mr-1"></i>成员管理</button><div class="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 class="text-2xl font-bold text-neutral-900">加入审批</h1><p class="mt-1 text-sm text-neutral-500">处理空间成员申请并保留审批历史。</p></div><select v-model="status" class="rounded-lg border bg-white px-3 py-2 text-sm" @change="load"><option value="pending">待处理</option><option value="approved">已通过</option><option value="rejected">已拒绝</option><option value="">全部</option></select></div><section class="rounded-xl border bg-white shadow-sm"><div v-if="loading" class="py-16 text-center text-neutral-400"><i class="fa fa-spinner fa-spin mr-1"></i>加载申请</div><div v-else-if="!requests.length" class="py-16 text-center text-sm text-neutral-400">暂无申请记录</div><div v-else class="divide-y"><div v-for="request in requests" :key="request.requestId" class="flex flex-wrap items-center justify-between gap-4 px-5 py-4"><div><p class="font-medium text-neutral-800">{{ request.userId }}</p><p class="mt-1 text-sm text-neutral-500">{{ request.requestMessage || '未填写申请说明' }}</p><p class="mt-1 text-xs text-neutral-400">提交于 {{ request.createdAt }}</p></div><div v-if="request.status === 'pending'" class="flex gap-2"><button class="rounded-lg bg-primary px-3 py-2 text-xs font-medium text-white" @click="review(request.requestId, 'approved')">批准</button><button class="rounded-lg border border-red-200 px-3 py-2 text-xs text-red-500" @click="review(request.requestId, 'rejected')">拒绝</button></div><span v-else class="rounded-full px-2.5 py-1 text-xs" :class="request.status === 'approved' ? 'bg-green-50 text-green-600' : 'bg-red-50 text-red-500'">{{ request.status === 'approved' ? '已通过' : '已拒绝' }}</span></div></div></section></div></main>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { listCollaborationApprovalsApi, reviewCollaborationApprovalApi, type SpaceJoinRequest } from '@/api/modules/space'; import { useToastStore } from '@/stores/toastStore'
const route = useRoute(); const router = useRouter(); const toast = useToastStore(); const spaceId = String(route.params.spaceId); const status = ref('pending'); const requests = ref<SpaceJoinRequest[]>([]); const loading = ref(false)
async function load() { loading.value = true; try { const res = await listCollaborationApprovalsApi(spaceId, status.value || undefined); requests.value = res.data || [] } catch { toast.showToast('审批列表加载失败', 'error') } finally { loading.value = false } }
async function review(id: number, action: 'approved' | 'rejected') { try { await reviewCollaborationApprovalApi(spaceId, id, action); toast.showToast(action === 'approved' ? '已批准申请' : '已拒绝申请', 'success'); await load() } catch { toast.showToast('审批操作失败', 'error') } }
onMounted(load)
</script>
