<template>
  <main class="min-h-screen bg-neutral-50 px-4 py-6 sm:px-6"><div class="mx-auto max-w-3xl"><button class="mb-5 text-sm text-neutral-500 hover:text-primary" @click="router.back()"><i class="fa fa-arrow-left mr-1"></i>返回</button><section class="rounded-2xl border bg-white p-6 shadow-sm sm:p-8"><h1 class="text-2xl font-bold text-neutral-900">空间设置</h1><p class="mt-1 text-sm text-neutral-500">调整空间资料、发现范围和加入策略。</p><form class="mt-8 space-y-5" @submit.prevent="save"><label class="block"><span class="mb-1 block text-sm font-medium text-neutral-700">空间名称</span><input v-model.trim="form.spaceName" required maxlength="64" class="w-full rounded-lg border px-3 py-2.5 text-sm outline-none focus:border-primary" /></label><label class="block"><span class="mb-1 block text-sm font-medium text-neutral-700">空间描述</span><textarea v-model="form.spaceDescription" maxlength="500" rows="4" class="w-full rounded-lg border px-3 py-2.5 text-sm outline-none focus:border-primary"></textarea></label><div class="grid gap-4 sm:grid-cols-2"><label class="block"><span class="mb-1 block text-sm font-medium text-neutral-700">可见性</span><select v-model="form.spaceVisibility" :disabled="space?.spaceType === 'personal'" class="w-full rounded-lg border px-3 py-2.5 text-sm"><option value="visible">可被发现</option><option value="hidden">仅成员可见</option><option value="private">私有</option></select></label><label class="block"><span class="mb-1 block text-sm font-medium text-neutral-700">加入策略</span><select v-model="form.joinPolicy" :disabled="space?.spaceType === 'personal'" class="w-full rounded-lg border px-3 py-2.5 text-sm"><option value="open">开放加入</option><option value="approval_required">需要审批</option><option value="invite_only">仅限邀请</option></select></label></div><div class="flex items-center justify-end gap-3 border-t pt-5"><button type="button" class="rounded-lg px-4 py-2 text-sm text-neutral-500 hover:bg-neutral-100" @click="router.back()">取消</button><button type="submit" class="rounded-lg bg-primary px-5 py-2 text-sm font-medium text-white disabled:opacity-50" :disabled="saving">{{ saving ? '保存中…' : '保存设置' }}</button></div></form></section></div></main>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { getSpaceApi, updateCollaborationSettingsApi, type SpaceInfo } from '@/api/modules/space'; import { useToastStore } from '@/stores/toastStore'
const route = useRoute(); const router = useRouter(); const toast = useToastStore(); const spaceId = String(route.params.spaceId); const space = ref<SpaceInfo | null>(null); const saving = ref(false); const form = reactive<{ spaceName: string; spaceDescription: string; spaceVisibility: string; joinPolicy: 'open' | 'approval_required' | 'invite_only' }>({ spaceName: '', spaceDescription: '', spaceVisibility: 'hidden', joinPolicy: 'approval_required' })
async function load() { try { const res = await getSpaceApi(spaceId); space.value = res.data; Object.assign(form, { spaceName: res.data.spaceName, spaceDescription: res.data.spaceDescription || '', spaceVisibility: res.data.spaceVisibility === 'public' ? 'visible' : (res.data.spaceVisibility || 'hidden'), joinPolicy: res.data.joinPolicy || 'approval_required' }) } catch { toast.showToast('空间设置加载失败', 'error') } }
async function save() { saving.value = true; try { await updateCollaborationSettingsApi(spaceId, form); toast.showToast('空间设置已保存', 'success'); await load() } catch { toast.showToast('保存失败，请检查权限', 'error') } finally { saving.value = false } }
onMounted(load)
</script>
