plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.7'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.project'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(18)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    maven { url 'https://maven.aliyun.com/repository/public' }
    maven { url 'https://maven.aliyun.com/repository/central' }
    maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }

    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.4'
    compileOnly 'org.projectlombok:lombok'
    // MySQL 驱动
    runtimeOnly 'com.mysql:mysql-connector-j'
    // AOP 核心依赖（Spring AOP + AspectJ）
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.statemachine:spring-statemachine-core:4.0.1'
    // BCrypt/PasswordEncoder
    implementation 'org.springframework.security:spring-security-crypto'
    // RabbitMQ 依赖
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    // Redis 依赖
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.apache.commons:commons-pool2'
    // JWT 生成与解析（jjwt）
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'
    // 邮件发送 JavaMailSender
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    // Thymeleaf 模板引擎（用于 HTML 邮件渲染）
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    // Jackson JSON 处理（已存在于boot，但这里显式声明以便于消息转换）
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    //OpenSearch依赖
    implementation 'org.opensearch.client:opensearch-rest-high-level-client:2.10.0'
    // SpringDoc OpenAPI（Swagger UI）- API 文档与测试
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'


    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:3.0.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
